AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
